Add a GitHub release jobs to the Circuit/Parachain Release pipelines

diff --git a/.github/workflows/circuit-release.yml b/.github/workflows/circuit-release.yml
--- a/.github/workflows/circuit-release.yml
+++ b/.github/workflows/circuit-release.yml
@@ -9,6 +9,8 @@ on:
       - circuit/**/Cargo.toml
       - circuit/**/Cargo.lock
       - .github/workflows/circuit-release.yml
+    tags:
+      - 'v*'
 
 env:
   RUST_BACKTRACE: 1
@@ -107,3 +109,81 @@ jobs:
           file: docker/circuit.Dockerfile
           cache-from: type=local,src=/tmp/.buildx-cache
           cache-to: type=local,dest=/tmp/.buildx-cache
+
+  release-on-github:
+    runs-on: ubuntu-20.04
+    needs: build-release
+    if: startsWith(github.ref, 'refs/tags/v')
+    steps:
+      - name: ☁ Checkout git repo
+        uses: actions/checkout@v2
+
+      - name: 📥 Download circuit
+        uses: actions/download-artifact@v2
+        with:
+          name: ${{ github.sha }}-artifacts
+          path: circuit/target/release/
+
+      - name: 🎱 Gzip circuit
+        run: |
+          gzip -c ./circuit/target/release/circuit \
+          > ./circuit/target/release/circuit.gz
+
+      - name: 🖐🏾 Fingerprint the gball
+        run: |
+          sha256sum -b ./circuit/target/release/circuit.gz \
+          | grep -oE '^[a-f0-9]+' \
+          > ./circuit/target/release/circuit.gz.sha256sum
+
+      - name: 🏷️ Get the version tag
+        run: echo "PUSHED_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
+
+      - name: 🖍️ Get the release name
+        run: |
+          release_name="$(git tag -l --format='%(contents:subject)' ${{ env.PUSHED_TAG }})"
+          release_name=${release_name:-${{ env.PUSHED_TAG }}}
+          echo "RELEASE_NAME=\"$release_name\"" >> $GITHUB_ENV
+
+      - name: 🖨️ Get the release notes
+        run: |
+          release_notes="$(sed -n '/## `${{ env.PUSHED_TAG }}/{:a;n;/##/b;p;ba}' ./CHANGELOG.md)"
+          if [[ -z "${release_notes// }" ]]; then
+            release_notes="$(sed -n '/## ${{ env.PUSHED_TAG }}/{:a;n;/##/b;p;ba}' ./CHANGELOG.md)"
+            if [[ -z "${release_notes// }" ]]; then
+              echo "failed parsing release notes for ${{ env.PUSHED_TAG }} from CHANGELOG.md" >&2
+              exit 1
+            fi
+          fi
+          echo "$release_notes" > ./circuit/target/release/notes.txt
+
+      - name: 🐙 Draft a prerelease
+        id: create_release
+        uses: actions/create-release@v1.1.4
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ env.PUSHED_TAG }}
+          release_name: ${{ env.RELEASE_NAME }}
+          body_path: ./circuit/target/release/notes.txt
+          draft: true
+          prerelease: true
+
+      - name: 🍔 Provide the sha256sum as a release asset
+        uses: actions/upload-release-asset@v1.0.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./circuit/target/release/circuit.gz.sha256sum
+          asset_name: t3rn-circuit-${{ env.PUSHED_TAG }}-x86_64-unknown-linux-gnu.gz.sha256sum
+          asset_content_type: text/plain
+
+      - name: 📦 Upload the circuit gball as a release asset
+        uses: actions/upload-release-asset@v1.0.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./circuit/target/release/circuit.gz
+          asset_name: t3rn-circuit-${{ env.PUSHED_TAG }}-x86_64-unknown-linux-gnu.gz
+          asset_content_type: application/gzip
